# Lightweight stage-I diagnostic, NOT an end-to-end DIFS example.
source("R/difs_core.R")
d <- readRDS("demo/demo_data.rds")
gate <- difs_gate_genes(d$logcounts, gate_rule="submitted", gate_k=d$k)
ranked <- difs_stage1_ranking(d$logcounts, gate_rule="submitted", gate_k=d$k)
again <- difs_stage1_ranking(d$logcounts, gate_rule="submitted", gate_k=d$k)
stopifnot(length(ranked)==length(gate), !anyDuplicated(ranked), identical(ranked,again))
cat("Stage-I diagnostic only; submitted gate max(0.05*N,35).\n")
cat(sprintf("Genes: %d cells: %d gate: %d\n",nrow(d$logcounts),ncol(d$logcounts),length(gate)))
cat("First 10: ",paste(head(ranked,10),collapse=", "),"\n",sep="")
cat("STAGE-I CHECK PASSED. Stage II has NOT been tested by this script.\n")
